apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-git
spec:
  generators:
    # matrix 'parent' generator
    - matrix:
        generators:
          # git generator, 'child' #1
          - git:
              repoURL: https://github.com/lloydsmithjr03/gitops-helm-dependency.git
              revision: HEAD
              directories:
                - path: root-chart/
          # cluster generator, 'child' #2
          - clusters:
              {}
  template:
    metadata:
      name: '{{path.basename}}-{{name}}'
    spec:
      project: default
      source:
        repoURL:  https://github.com/lloydsmithjr03/gitops-helm-dependency.git
        targetRevision: 0.1.0
        path: '{{path}}'
        helm:
          releaseName: '{{path.basename}}-{{name}}'
      destination:
        server: '{{server}}'
        namespace: '{{path.basename}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
